apiVersion: v1
kind: Config
clusters:
- name: "swe-extra-credit"
  cluster:
    server: "https://ec2-52-207-22-65.compute-1.amazonaws.com/k8s/clusters/c-m-7btz9pxx"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2VENDQ\
      VdPZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQkdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\
      kdsemRHVnVaWEl0YjNKbk1TWXdKQVlEVlFRRERCMWtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRkFNV\
      GMwTlRZeApPRGMyTWpBZUZ3MHlOVEEwTWpVeU1qQTJNREphRncwek5UQTBNak15TWpBMk1ESmFNR\
      Vl4SERBYUJnTlZCQW9UCkUyUjVibUZ0YVdOc2FYTjBaVzVsY2kxdmNtY3hKakFrQmdOVkJBTU1IV\
      1I1Ym1GdGFXTnNhWE4wWlc1bGNpMWoKWVVBeE56UTFOakU0TnpZeU1Ga3dFd1lIS29aSXpqMENBU\
      VlJS29aSXpqMERBUWNEUWdBRXc5QWczeFhqb1pBVgo0UW1ZelFsSVNMdEZmNkRYa2FISXE5ZTJ0U\
      TcrNG9SeDlMdElybzRKaFZOWnVtUU9xU20zbTJraFFTUDNHTXNrClhVcGJyQjJYRWFOQ01FQXdEZ\
      1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWUQKVlIwT0JCWUVGT\
      S9mT01WZEVRRVNuVWZtY0Q3c1JqbnlQWDdJTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSUYxNQpzV\
      3J3V282WGJsdlZIQTkyampuN2Y1cTgyK3UxS1hLdzgxbUgwUXBGQWlFQTV2UWJkM3N4MnB1RHowc\
      XhDVlo5CkNEazBUK3J2azdEUDNVKzBtWS9QSHdnPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"

users:
- name: "swe-extra-credit"
  user:
    token: "kubeconfig-user-wjk5964b2p:js2hfg6bk7nz7hkdqvhmxqwtskrqm8q7jq8lhnqvltglsqpn6l49fx"


contexts:
- name: "swe-extra-credit"
  context:
    user: "swe-extra-credit"
    cluster: "swe-extra-credit"

current-context: "swe-extra-credit"
