apiVersion: v1
kind: Config
clusters:
- name: "swe645-hw2"
  cluster:
    server: "https://ec2-52-3-136-186.compute-1.amazonaws.com/k8s/clusters/c-m-q4fbhhkw"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2VENDQ\
      VdPZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQkdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\
      kdsemRHVnVaWEl0YjNKbk1TWXdKQVlEVlFRRERCMWtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRkFNV\
      GMwTURZMQpNemcwTVRBZUZ3MHlOVEF5TWpjeE1EVTNNakZhRncwek5UQXlNalV4TURVM01qRmFNR\
      Vl4SERBYUJnTlZCQW9UCkUyUjVibUZ0YVdOc2FYTjBaVzVsY2kxdmNtY3hKakFrQmdOVkJBTU1IV\
      1I1Ym1GdGFXTnNhWE4wWlc1bGNpMWoKWVVBeE56UXdOalV6T0RReE1Ga3dFd1lIS29aSXpqMENBU\
      VlJS29aSXpqMERBUWNEUWdBRU1LamJWRmNHR1oxdgptek8vR2x5Q081RHRwY3pJN3hmNDdDTUFPV\
      moyWStRT1hnc1BvSy9tSFBZU2prY3U5OXBkNVB0TUlxQkRUVXRkCmZleGgyTUg1RzZOQ01FQXdEZ\
      1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWUQKVlIwT0JCWUVGS\
      2xjTEcvUlVGdG1RcWMyQ2xCeEtFM01jaDNnTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSVFEVwp0T\
      0xNNGhMbEx2d29zdFYzV1NRUEwyOFIvTkJIYVlmaHc4T2dFSkFTMWdJZ1pVRWpXRWNZVWY3UUY5M\
      E1PQzFZCnZtdTk5M2k4Rks0WmhiRlE4RWo5M1k0PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"

users:
- name: "swe645-hw2"
  user:
    token: "kubeconfig-user-p9hjqjxq9q:cdxhstmftr8g4bwrwrgknk5gzdspqvz7g7bj6hh4gf962cfdhpss2g"


contexts:
- name: "swe645-hw2"
  context:
    user: "swe645-hw2"
    cluster: "swe645-hw2"

current-context: "swe645-hw2"
