apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["default/survey-deployment"]'
    management.cattle.io/ui-managed: 'true'
  creationTimestamp: '2025-04-25T22:23:30Z'
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:field.cattle.io/targetWorkloadIds: {}
            f:management.cattle.io/ui-managed: {}
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":8000,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: agent
      operation: Update
      time: '2025-04-25T22:23:30Z'
  name: survey-deployment
  namespace: default
  resourceVersion: '6031'
  uid: f16630c8-4aaf-4a30-9952-c09ca8a96486
spec:
  clusterIP: 10.43.64.155
  clusterIPs:
    - 10.43.64.155
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: nodeport
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-default-survey-deployment
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
