apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["default/survey-deployment"]'
    management.cattle.io/ui-managed: 'true'
  creationTimestamp: '2025-02-27T11:09:38Z'
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:field.cattle.io/targetWorkloadIds: {}
            f:management.cattle.io/ui-managed: {}
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":8080,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: agent
      operation: Update
      time: '2025-02-27T11:09:38Z'
  name: survey-deployment
  namespace: default
  resourceVersion: '4363'
  uid: 3579b31d-23ca-4a64-b42b-67888ac8b1be
spec:
  clusterIP: 10.43.31.130
  clusterIPs:
    - 10.43.31.130
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: service-port
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-default-survey-deployment
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
