apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: >-
      [{"addresses":["172.31.39.123"],"port":31845,"protocol":"TCP","serviceName":"default:survey-deployment-nodeport","allNodes":true}]
    field.cattle.io/targetWorkloadIds: '["default/survey-deployment"]'
    management.cattle.io/ui-managed: 'true'
  creationTimestamp: '2025-04-25T22:23:30Z'
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:field.cattle.io/publicEndpoints: {}
            f:field.cattle.io/targetWorkloadIds: {}
            f:management.cattle.io/ui-managed: {}
        f:spec:
          f:externalTrafficPolicy: {}
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":8000,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: agent
      operation: Update
      time: '2025-04-25T22:23:30Z'
  name: survey-deployment-nodeport
  namespace: default
  resourceVersion: '6039'
  uid: 32a6680d-2d2e-494a-99d5-46154f814cc0
spec:
  clusterIP: 10.43.28.171
  clusterIPs:
    - 10.43.28.171
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: nodeport
      nodePort: 31845
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-default-survey-deployment
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
