apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: >-
      [{"addresses":["172.31.38.206"],"port":31221,"protocol":"TCP","serviceName":"default:survey-deployment-nodeport","allNodes":true}]
    field.cattle.io/targetWorkloadIds: '["default/survey-deployment"]'
    management.cattle.io/ui-managed: 'true'
  creationTimestamp: '2025-02-27T11:09:38Z'
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:field.cattle.io/publicEndpoints: {}
            f:field.cattle.io/targetWorkloadIds: {}
            f:management.cattle.io/ui-managed: {}
        f:spec:
          f:externalTrafficPolicy: {}
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":8080,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: agent
      operation: Update
      time: '2025-02-27T11:09:38Z'
  name: survey-deployment-nodeport
  namespace: default
  resourceVersion: '4370'
  uid: 72adccac-118f-441b-99cd-1407e52948b5
spec:
  clusterIP: 10.43.127.90
  clusterIPs:
    - 10.43.127.90
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: service-port
      nodePort: 31221
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-default-survey-deployment
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
