apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  annotations:
    field.cattle.io/creatorId: user-wjk59
    provisioning.cattle.io/management-cluster-display-name: swe-extra-credit
  creationTimestamp: '2025-04-25T22:08:54Z'
  finalizers:
    - wrangler.cattle.io/provisioning-cluster-remove
    - wrangler.cattle.io/rke-cluster-remove
    - wrangler.cattle.io/cloud-config-secret-remover
  generation: 2
  managedFields:
    - apiVersion: provisioning.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:provisioning.cattle.io/management-cluster-display-name: {}
          f:finalizers:
            .: {}
            v:"wrangler.cattle.io/provisioning-cluster-remove": {}
            v:"wrangler.cattle.io/rke-cluster-remove": {}
        f:spec:
          .: {}
          f:kubernetesVersion: {}
          f:localClusterAuthEndpoint: {}
          f:rkeConfig:
            .: {}
            f:chartValues:
              .: {}
              f:rke2-calico: {}
            f:dataDirectories: {}
            f:etcd:
              .: {}
              f:snapshotRetention: {}
              f:snapshotScheduleCron: {}
            f:machineGlobalConfig:
              .: {}
              f:cni: {}
              f:disable-kube-proxy: {}
              f:etcd-expose-metrics: {}
            f:machinePoolDefaults: {}
            f:machineSelectorConfig: {}
            f:registries: {}
            f:upgradeStrategy:
              .: {}
              f:controlPlaneConcurrency: {}
              f:controlPlaneDrainOptions:
                .: {}
                f:deleteEmptyDirData: {}
                f:disableEviction: {}
                f:enabled: {}
                f:force: {}
                f:gracePeriod: {}
                f:ignoreDaemonSets: {}
                f:ignoreErrors: {}
                f:postDrainHooks: {}
                f:preDrainHooks: {}
                f:skipWaitForDeleteTimeoutSeconds: {}
                f:timeout: {}
              f:workerConcurrency: {}
              f:workerDrainOptions:
                .: {}
                f:deleteEmptyDirData: {}
                f:disableEviction: {}
                f:enabled: {}
                f:force: {}
                f:gracePeriod: {}
                f:ignoreDaemonSets: {}
                f:ignoreErrors: {}
                f:postDrainHooks: {}
                f:preDrainHooks: {}
                f:skipWaitForDeleteTimeoutSeconds: {}
                f:timeout: {}
      manager: rancher
      operation: Update
      time: '2025-04-25T22:08:55Z'
    - apiVersion: provisioning.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            v:"wrangler.cattle.io/cloud-config-secret-remover": {}
      manager: rancher-v2.11.1-secret-migrator
      operation: Update
      time: '2025-04-25T22:08:56Z'
    - apiVersion: provisioning.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:agentDeployed: {}
          f:clientSecretName: {}
          f:clusterName: {}
          f:conditions: {}
          f:fleetWorkspaceName: {}
          f:observedGeneration: {}
          f:ready: {}
      manager: rancher
      operation: Update
      subresource: status
      time: '2025-04-25T22:52:35Z'
  name: swe-extra-credit
  namespace: fleet-default
  resourceVersion: '18206'
  uid: 7d05d5c3-8746-41f4-b2b9-31001b9746fc
spec:
  kubernetesVersion: v1.32.3+rke2r1
  localClusterAuthEndpoint: {}
  rkeConfig:
    chartValues:
      rke2-calico: {}
    dataDirectories: {}
    etcd:
      snapshotRetention: 5
      snapshotScheduleCron: 0 */5 * * *
    machineGlobalConfig:
      cni: calico
      disable-kube-proxy: false
      etcd-expose-metrics: false
    machinePoolDefaults: {}
    machineSelectorConfig:
      - config:
          protect-kernel-defaults: false
    registries: {}
    upgradeStrategy:
      controlPlaneConcurrency: '1'
      controlPlaneDrainOptions:
        deleteEmptyDirData: true
        disableEviction: false
        enabled: false
        force: false
        gracePeriod: -1
        ignoreDaemonSets: true
        ignoreErrors: false
        postDrainHooks: null
        preDrainHooks: null
        skipWaitForDeleteTimeoutSeconds: 0
        timeout: 120
      workerConcurrency: '1'
      workerDrainOptions:
        deleteEmptyDirData: true
        disableEviction: false
        enabled: false
        force: false
        gracePeriod: -1
        ignoreDaemonSets: true
        ignoreErrors: false
        postDrainHooks: null
        preDrainHooks: null
        skipWaitForDeleteTimeoutSeconds: 0
        timeout: 120
status:
  agentDeployed: true
  clientSecretName: swe-extra-credit-kubeconfig
  clusterName: c-m-7btz9pxx
  conditions:
    - lastUpdateTime: '2025-04-25T22:12:07Z'
      status: 'False'
      type: Reconciling
    - lastUpdateTime: '2025-04-25T22:08:55Z'
      status: 'False'
      type: Stalled
    - lastUpdateTime: '2025-04-25T22:52:24Z'
      status: 'True'
      type: Created
    - lastUpdateTime: '2025-04-25T22:52:35Z'
      status: 'True'
      type: RKECluster
    - lastUpdateTime: '2025-04-25T22:08:55Z'
      status: 'True'
      type: BackingNamespaceCreated
    - lastUpdateTime: '2025-04-25T22:08:55Z'
      status: 'True'
      type: DefaultProjectCreated
    - lastUpdateTime: '2025-04-25T22:08:56Z'
      status: 'True'
      type: SystemProjectCreated
    - lastUpdateTime: '2025-04-25T22:52:25Z'
      status: 'True'
      type: Updated
    - lastUpdateTime: '2025-04-25T22:52:25Z'
      status: 'True'
      type: Provisioned
    - lastUpdateTime: '2025-04-25T22:52:35Z'
      status: 'True'
      type: Ready
    - lastUpdateTime: '2025-04-25T22:08:56Z'
      status: 'True'
      type: InitialRolesPopulated
    - lastUpdateTime: '2025-04-25T22:08:57Z'
      status: 'True'
      type: CreatorMadeOwner
    - lastUpdateTime: '2025-04-25T22:08:57Z'
      status: 'True'
      type: NoDiskPressure
    - lastUpdateTime: '2025-04-25T22:08:57Z'
      status: 'True'
      type: NoMemoryPressure
    - lastUpdateTime: '2025-04-25T22:08:57Z'
      status: 'True'
      type: SecretsMigrated
    - lastUpdateTime: '2025-04-25T22:52:24Z'
      status: 'True'
      type: Connected
    - lastUpdateTime: '2025-04-25T22:08:57Z'
      status: 'True'
      type: ServiceAccountSecretsMigrated
    - lastUpdateTime: '2025-04-25T22:08:58Z'
      status: 'True'
      type: RKESecretsMigrated
    - lastUpdateTime: '2025-04-25T22:08:58Z'
      status: 'True'
      type: ACISecretsMigrated
    - status: Unknown
      type: PreBootstrapped
    - lastUpdateTime: '2025-04-25T22:11:38Z'
      status: 'True'
      type: AgentTlsStrictCheck
    - lastUpdateTime: '2025-04-25T22:11:38Z'
      status: 'True'
      type: SystemAccountCreated
    - lastUpdateTime: '2025-04-25T22:11:40Z'
      status: 'True'
      type: AgentDeployed
    - lastUpdateTime: '2025-04-25T22:11:40Z'
      status: 'True'
      type: GlobalAdminsSynced
    - lastUpdateTime: '2025-04-25T22:12:07Z'
      status: 'True'
      type: Waiting
  fleetWorkspaceName: fleet-default
  observedGeneration: 2
  ready: true
