# Generated by Django 5.2 on 2025-04-21 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('street_address', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('zip', models.CharField(blank=True, max_length=10)),
                ('telephone_number', models.CharField(blank=True, max_length=15)),
                ('liked_most', models.CharField(blank=True, max_length=100)),
                ('interest_source', models.CharField(blank=True, max_length=100)),
                ('recommendation', models.CharField(blank=True, max_length=100)),
                ('date_of_survey', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
